import type { CampaignPerf } from "./performance";

/** A campaign row with full metrics, for the exportable report. */
export interface ReportRow extends CampaignPerf {
  impressions: number;
  clicks: number;
}

function money(n: number): string {
  return `₹${Math.round(n).toLocaleString("en-IN")}`;
}

function rank(a: ReportRow, b: ReportRow): number {
  if (a.leads !== b.leads) return b.leads - a.leads;
  return (a.cpl ?? Infinity) - (b.cpl ?? Infinity);
}

/**
 * Render a Markdown performance report for a business — a portable, human- and
 * AI-readable log of what each campaign targeted and the results it produced.
 */
export function buildPerformanceReport(input: {
  businessName: string;
  generatedAt: Date;
  rows: ReportRow[];
}): string {
  const { businessName, generatedAt, rows } = input;
  const delivered = rows.filter((r) => r.leads > 0 || r.spend > 0);
  const totalLeads = delivered.reduce((s, r) => s + r.leads, 0);
  const totalSpend = delivered.reduce((s, r) => s + r.spend, 0);
  const blendedCpl = totalLeads > 0 ? totalSpend / totalLeads : null;

  const lines: string[] = [];
  lines.push(`# AdBrain Performance Report — ${businessName}`);
  lines.push("");
  lines.push(`_Generated ${generatedAt.toISOString().slice(0, 10)}_`);
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push(`- Campaigns: ${rows.length} (${delivered.length} with delivery)`);
  lines.push(`- Total leads: ${totalLeads}`);
  lines.push(`- Total spend: ${money(totalSpend)}`);
  lines.push(
    `- Blended cost per lead: ${blendedCpl != null ? money(blendedCpl) : "—"}`,
  );
  lines.push("");

  if (delivered.length) {
    const best = [...delivered].sort(rank)[0];
    lines.push(
      `**Best so far:** "${best.name}"${
        best.angles.length ? ` (${best.angles.join("/")})` : ""
      }${best.cpl != null ? ` at ${money(best.cpl)}/lead` : ""}.`,
    );
    lines.push("");
  }

  lines.push("## Campaigns");
  lines.push("");
  lines.push(
    "| Campaign | Angle | Area | Budget/day | Impressions | Clicks | Leads | Cost/lead | Status |",
  );
  lines.push("| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
  for (const r of [...rows].sort(rank)) {
    lines.push(
      `| ${r.name} | ${r.angles.join("/") || "—"} | ${r.area ?? "—"} | ${
        r.dailyBudget != null ? money(r.dailyBudget) : "—"
      } | ${r.impressions} | ${r.clicks} | ${r.leads} | ${
        r.cpl != null ? money(r.cpl) : "—"
      } | ${r.status} |`,
    );
  }
  lines.push("");
  lines.push(
    "_Generated by AdBrain. Cost per lead is spend ÷ leads for each campaign._",
  );

  return lines.join("\n");
}
