import type { CampaignPerf } from "./performance";

/** A campaign row with full metrics, for the exportable report. */
export interface ReportRow extends CampaignPerf {
  impressions: number;
  clicks: number;
}

function money(n: number): string {
  return `₹${Math.round(n).toLocaleString("en-IN")}`;
}

function markdownText(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/[\\`*_[\]|]/g, "\\$&").replace(/[\r\n]+/g, " ");
}

function rank(a: ReportRow, b: ReportRow): number {
  if (a.leads !== b.leads) return b.leads - a.leads;
  return (a.cpl ?? Infinity) - (b.cpl ?? Infinity);
}

/**
 * Render a Markdown performance report for a business — a portable, human- and
 * AI-readable log of what each campaign targeted and the results it produced.
 */
export function buildPerformanceReport(input: {
  businessName: string;
  generatedAt: Date;
  rows: ReportRow[];
}): string {
  const { businessName, generatedAt, rows } = input;
  const delivered = rows.filter((r) => r.leads > 0 || (r.conversations ?? 0) > 0 || r.spend > 0 || r.impressions > 0 || r.clicks > 0);
  const destination = (row: ReportRow) => row.destination;
  const leadCampaigns = delivered.filter(campaign => destination(campaign) === "instant_form");
  const messagingCampaigns = delivered.filter(campaign => destination(campaign) === "whatsapp");
  const unavailableCampaigns = delivered.filter(campaign => !["instant_form", "whatsapp"].includes(destination(campaign)));
  const conversationsComplete = messagingCampaigns.every(campaign => campaign.conversations != null);
  const totalLeads = leadCampaigns.reduce((sum, campaign) => sum + campaign.leads, 0);
  const leadSpend = leadCampaigns.reduce((sum, campaign) => sum + campaign.spend, 0);
  const conversations = messagingCampaigns.reduce((sum, campaign) => sum + (campaign.conversations ?? 0), 0);
  const conversationSpend = messagingCampaigns.reduce((sum, campaign) => sum + campaign.spend, 0);
  const totalSpend = delivered.reduce((s, r) => s + r.spend, 0);
  const blendedCpl = totalLeads > 0 ? leadSpend / totalLeads : null;

  const lines: string[] = [];
  lines.push(`# AdBrain Performance Report — ${markdownText(businessName)}`);
  lines.push("");
  lines.push(`_Generated ${generatedAt.toISOString().slice(0, 10)}_`);
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push(`- Campaigns: ${rows.length} (${delivered.length} with delivery)`);
  lines.push(`- Total leads: ${totalLeads}`);
  lines.push(`- Total spend: ${money(totalSpend)}`);
  if (messagingCampaigns.length) {
    lines.push(`- WhatsApp conversations started: ${conversationsComplete ? conversations : "Unavailable (refresh required)"}`);
    lines.push(`- WhatsApp spend: ${money(conversationSpend)}`);
    lines.push(`- Cost per WhatsApp conversation: ${conversationsComplete && conversations > 0 ? money(conversationSpend / conversations) : "—"}`);
    lines.push("- Lead totals and blended lead cost exclude WhatsApp campaigns. Conversations are not verified leads or sales.");
  }
  if (unavailableCampaigns.length) lines.push(`- Campaigns excluded from outcome comparisons: ${unavailableCampaigns.length} (destination unknown, mixed, or unsupported). Their spend remains in total spend.`);
  lines.push(
    `- Blended cost per lead: ${blendedCpl != null ? money(blendedCpl) : "—"}`,
  );
  lines.push("");

  const best = [...leadCampaigns].filter((campaign) => campaign.leads > 0).sort(rank)[0];
  if (best) {
    lines.push(
      `**Best so far:** "${markdownText(best.name)}"${
        best.angles.length ? ` (${markdownText(best.angles.join("/"))})` : ""
      }${best.cpl != null ? ` at ${money(best.cpl)}/lead` : ""}.`,
    );
    lines.push("");
  }

  lines.push("## Campaigns");
  lines.push("");
  lines.push(
    "| Campaign | Angle | Area | Budget/day | Impressions | Clicks | Leads | Cost/lead | WhatsApp conversations | Cost/conversation | Status |",
  );
  lines.push("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |");
  for (const r of [...rows].sort(rank)) {
    lines.push(
      `| ${markdownText(r.name)} | ${markdownText(r.angles.join("/") || "—")} | ${markdownText(r.area ?? "—")} | ${
        r.dailyBudget != null ? money(r.dailyBudget) : "—"
      } | ${r.impressions} | ${r.clicks} | ${destination(r) === "instant_form" ? r.leads : "—"} | ${
        destination(r) === "instant_form" && r.cpl != null ? money(r.cpl) : "—"
      } | ${destination(r) === "whatsapp" ? r.conversations ?? "—" : "—"} | ${destination(r) === "whatsapp" && r.conversations != null && r.costPerConversation != null ? money(r.costPerConversation) : "—"} | ${markdownText(r.status)} |`,
    );
  }
  lines.push("");
  lines.push(
    "_Generated by AdBrain. Cost per lead is spend ÷ leads for each campaign._",
  );

  return lines.join("\n");
}
