import type { Metadata } from "next";
import { JsonLd } from "@/components/json-ld";
import { LegalPage } from "@/components/legal-page";
import { contentPageGraph } from "@/lib/seo/jsonLd";

const TITLE = "Terms of Service";
const DESCRIPTION =
  "The terms that govern your use of AdBrain, including acceptable use, AI-generated content, ad spend, and liability.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: "/terms" },
  openGraph: { title: `${TITLE} — AdBrain`, description: DESCRIPTION, url: "/terms" },
};

export default function TermsPage() {
  return (
    <>
      <JsonLd
        data={contentPageGraph({ path: "/terms", name: TITLE, description: DESCRIPTION })}
      />
      <LegalPage title={TITLE} updated="13 August 2026">
        <p>
          These terms govern your use of AdBrain. By creating an account or using
          the service you agree to them. If you do not agree, do not use AdBrain.
        </p>

        <h2>The service</h2>
        <p>
          AdBrain generates ad creatives and helps you plan and launch
          lead-generation campaigns on Meta. Campaigns are created in a paused
          state — nothing is spent until you review and activate them.
        </p>

        <h2>Your account</h2>
        <p>
          You are responsible for your account, for keeping your credentials
          secure, and for all activity under your account. You must provide
          accurate information and be authorised to run ads for the business you
          add.
        </p>

        <h2>Acceptable use</h2>
        <ul>
          <li>Do not use AdBrain for unlawful, deceptive, or harmful advertising.</li>
          <li>Do not violate Meta&rsquo;s advertising policies or platform terms.</li>
          <li>Do not attempt to abuse, overload, reverse-engineer, or disrupt the service.</li>
          <li>Do not generate content that infringes others&rsquo; rights or is discriminatory, misleading, or prohibited.</li>
        </ul>

        <h2>AI-generated content</h2>
        <p>
          Creatives (images and copy) are generated by AI and may contain errors
          or claims that are not accurate for your business. You are responsible
          for reviewing and approving every ad before it runs, and for ensuring it
          is truthful and compliant. AdBrain does not guarantee any specific
          results, reach, or number of leads.
        </p>

        <h2>Ad spend</h2>
        <p>
          Your advertising budget is charged by Meta directly, according to the
          budget you set. AdBrain does not bill you for ad spend and is not
          responsible for charges made by Meta.
        </p>

        <h2>Third-party services</h2>
        <p>
          AdBrain relies on third parties (including Meta, our hosting and
          database providers, and AI providers). Your use of those services
          through AdBrain is also subject to their terms.
        </p>

        <h2>No warranty</h2>
        <p>
          The service is provided &ldquo;as is&rdquo; without warranties of any
          kind, to the fullest extent permitted by law. We do not warrant that the
          service will be uninterrupted, error-free, or fit for a particular
          purpose.
        </p>

        <h2>Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, AdBrain and its operator are not
          liable for any indirect, incidental, or consequential damages, or for
          lost profits, revenue, data, or ad spend, arising from your use of the
          service.
        </p>

        <h2>Termination</h2>
        <p>
          You may stop using AdBrain at any time. We may suspend or terminate
          access if you breach these terms or use the service in a way that
          creates risk or legal exposure.
        </p>

        <h2>Changes</h2>
        <p>
          We may update these terms. Continued use after changes means you accept
          the updated terms.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about these terms? Email{" "}
          <a href="mailto:hello@adbrain.vanshul.com">hello@adbrain.vanshul.com</a>.
        </p>
      </LegalPage>
    </>
  );
}
