import type { Metadata } from "next";
import { JsonLd } from "@/components/json-ld";
import { LegalPage } from "@/components/legal-page";
import { contentPageGraph } from "@/lib/seo/jsonLd";

const TITLE = "Privacy Policy";
const DESCRIPTION =
  "How AdBrain collects, uses, stores, and protects your data and the lead information generated by your ad campaigns.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: "/privacy" },
  openGraph: { title: `${TITLE} — AdBrain`, description: DESCRIPTION, url: "/privacy" },
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <JsonLd
        data={contentPageGraph({ path: "/privacy", name: TITLE, description: DESCRIPTION })}
      />
      <LegalPage title={TITLE} updated="13 August 2026">
        <p>
          AdBrain (&ldquo;AdBrain&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) helps businesses create ad
          creatives and run lead-generation campaigns on Meta (Facebook and
          Instagram). This policy explains what data we collect, why, and the
          choices you have. By using AdBrain you agree to this policy.
        </p>

        <h2>Information we collect</h2>
        <ul>
          <li>
            <strong>Account data.</strong> Your email address and authentication
            details, handled by our authentication provider when you sign in.
          </li>
          <li>
            <strong>Brand data.</strong> The business details you add to your
            Brand Brain — name, description, industry, brand voice, colours,
            offers, service areas, and any custom instructions or assets you
            upload.
          </li>
          <li>
            <strong>Campaign &amp; lead data.</strong> When you connect a Meta ad
            account and run campaigns, we store campaign settings, performance
            metrics, and the leads your ads generate (which may include a
            person&rsquo;s name, email, phone number, and their answers to your
            lead form).
          </li>
          <li>
            <strong>Usage data.</strong> Privacy-friendly, cookieless analytics
            about how the product is used, to improve it.
          </li>
        </ul>

        <h2>How we use your data</h2>
        <ul>
          <li>To generate ad creatives and campaign plans on your behalf.</li>
          <li>To create and manage your Meta campaigns and report on results.</li>
          <li>To collect and display the leads your campaigns generate.</li>
          <li>To operate, secure, and improve the service.</li>
        </ul>

        <h2>Third-party services</h2>
        <p>To provide AdBrain we share data with service providers, only as needed:</p>
        <ul>
          <li>
            <strong>Meta Platforms</strong> — to create campaigns and retrieve
            performance and lead data, subject to Meta&rsquo;s own terms and
            policies.
          </li>
          <li>
            <strong>Supabase</strong> — database, authentication, and file
            storage.
          </li>
          <li>
            <strong>AI providers</strong> — brand details and briefs are sent to
            large-language-model and image-generation providers to produce
            creatives. We do not sell your data, and we do not use it to train
            third-party models beyond generating your requested output.
          </li>
        </ul>

        <h2>Data retention</h2>
        <p>
          We keep your data for as long as your account is active. You can delete
          creatives, campaigns, and leads at any time from within the app.
          Deleting your account removes your associated data, subject to any
          records we must keep for legal or security reasons.
        </p>

        <h2>Security</h2>
        <p>
          Data is protected with row-level security so that only you can access
          your business&rsquo;s data, transport encryption (HTTPS), and access
          controls on our infrastructure. No system is perfectly secure, but we
          take reasonable measures to protect your information.
        </p>

        <h2>Your rights</h2>
        <p>
          You can access, correct, export, or delete your data from within the
          app, or by contacting us. If you handle other people&rsquo;s personal
          data (your leads), you are the controller of that data and are
          responsible for having a lawful basis to collect and contact them.
        </p>
        <p>
          For formal deletion requests, see our {" "}
          <a href="/data-deletion">Data Deletion Instructions</a> page.
        </p>

        <h2>Children</h2>
        <p>AdBrain is a business tool and is not directed to children under 16.</p>

        <h2>Changes</h2>
        <p>
          We may update this policy. Material changes will be reflected by the
          &ldquo;last updated&rdquo; date above.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about privacy? Email{" "}
          <a href="mailto:privacy@adbrain.vanshul.com">privacy@adbrain.vanshul.com</a>.
        </p>
      </LegalPage>
    </>
  );
}
