import { NextResponse } from "next/server";
import { logEvent } from "@/lib/audit";
import { getEnv } from "@/lib/env";
import {
  MetaError,
  type CreativeInput,
  type LeadForm,
} from "@/lib/meta/client";
import { metaClientForBusiness } from "@/lib/meta/credentials";
import { getPrimaryBusiness } from "@/lib/supabase/queries";
import { createClient } from "@/lib/supabase/server";
import type { Json } from "@/lib/types";

export const runtime = "nodejs";
export const maxDuration = 60;

interface RunBody {
  rounds?: number;
  createDraftCampaigns?: boolean;
  campaignsPerRound?: number;
}

interface RoundSummary {
  round: number;
  calls: number;
  campaignsSeen: number;
  insightsFetched: number;
  formsSeen: number;
  leadsFetched: number;
  campaignsCreated: number;
  errors: string[];
}

function clampInt(value: unknown, min: number, max: number, fallback: number): number {
  const n = Number(value);
  if (!Number.isFinite(n)) return fallback;
  return Math.max(min, Math.min(max, Math.floor(n)));
}

function isAllowed(email: string | null | undefined): boolean {
  const env = getEnv();
  const allowlist = env.TRAFFIC_GENERATOR_ALLOWED_EMAILS.map((v) =>
    v.toLowerCase(),
  );
  // No allowlist configured means "allow any authenticated user".
  if (!allowlist.length) return true;
  if (!email) return false;
  return allowlist.includes(email.toLowerCase());
}

async function createProbeCampaign(args: {
  businessId: string;
  businessName: string;
  businessWebsite: string | null;
  round: number;
  forms: LeadForm[];
}): Promise<{ created: boolean; reason?: string; metaCampaignId?: string }> {
  const supabase = await createClient();
  const meta = await metaClientForBusiness(args.businessId);
  if (!meta) return { created: false, reason: "Meta is not configured" };

  const leadFormId = args.forms[0]?.id;
  if (!leadFormId) return { created: false, reason: "No active lead form" };

  const { data: creatives } = await supabase
    .from("creatives")
    .select("id,image_url,headline,primary_text,cta")
    .eq("business_id", args.businessId)
    .eq("status", "approved")
    .limit(3);

  const usable = (creatives ?? []).filter((c) => c.image_url && c.headline);
  const creativePayload: CreativeInput[] = usable.map((c) => ({
    imageUrl: c.image_url as string,
    headline: c.headline ?? "AdBrain creative",
    message: c.primary_text ?? "Generated by AdBrain",
    cta: c.cta,
  }));
  if (!creativePayload.length) {
    creativePayload.push({
      imageUrl:
        "https://dummyimage.com/1200x628/0f172a/ffffff.png&text=AdBrain+Traffic+Probe",
      headline: "AdBrain traffic probe",
      message: "Paused campaign used to validate Marketing API integration.",
      cta: "Learn More",
    });
  }

  const campaignName = `${args.businessName} traffic probe ${new Date()
    .toISOString()
    .slice(0, 16)} r${args.round}`;

  const result = await meta.createLeadCampaign({
    name: campaignName,
    dailyBudgetRupees: 100,
    leadFormId,
    link: args.businessWebsite || getEnv().NEXT_PUBLIC_SITE_URL,
    creatives: creativePayload,
  });

  const { data: row, error } = await supabase
    .from("campaigns")
    .insert({
      business_id: args.businessId,
      name: campaignName,
      objective: "leads",
      daily_budget: 100,
      status: "paused",
      meta_campaign_id: result.campaignId,
      meta_adset_id: result.adSetId,
      meta_ad_ids: result.adIds,
      creative_ids: usable.map((c) => c.id),
      raw: {
        source: "internal_meta_traffic_runner",
        leadFormId,
        adSetIds: result.adSetIds,
        destination: result.destination,
        usedFallbackCreative: usable.length === 0,
      } as unknown as Json,
    })
    .select("id")
    .single();

  if (error) throw error;

  await logEvent({
    businessId: args.businessId,
    action: "campaign.create.traffic_probe",
    entityType: "campaign",
    entityId: row.id,
    metaObjectId: result.campaignId,
    reason: "Created paused campaign for Meta review traffic generation",
    details: {
      leadFormId,
      creatives: creativePayload.length,
      adIds: result.adIds.length,
      usedFallbackCreative: usable.length === 0,
    },
  });

  return { created: true, metaCampaignId: result.campaignId };
}

export async function POST(req: Request) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!isAllowed(user.email)) {
    return NextResponse.json(
      {
        error:
          "Forbidden. Add your email to TRAFFIC_GENERATOR_ALLOWED_EMAILS to enable this endpoint.",
      },
      { status: 403 },
    );
  }

  const body = (await req.json().catch(() => ({}))) as RunBody;
  const env = getEnv();
  const rounds = clampInt(body.rounds, 1, env.TRAFFIC_GENERATOR_MAX_ROUNDS, 5);
  const createDraftCampaigns = body.createDraftCampaigns === true;
  const campaignsPerRound = clampInt(body.campaignsPerRound, 1, 3, 1);

  const business = await getPrimaryBusiness();
  if (!business) {
    return NextResponse.json({ error: "No business found" }, { status: 400 });
  }

  const meta = await metaClientForBusiness(business.id);
  if (!meta) {
    return NextResponse.json({ error: "Meta is not configured" }, { status: 400 });
  }

  const roundsSummary: RoundSummary[] = [];
  let totalCalls = 0;
  let totalCreated = 0;

  for (let i = 1; i <= rounds; i++) {
    const summary: RoundSummary = {
      round: i,
      calls: 0,
      campaignsSeen: 0,
      insightsFetched: 0,
      formsSeen: 0,
      leadsFetched: 0,
      campaignsCreated: 0,
      errors: [],
    };

    let forms: LeadForm[] = [];

    try {
      const campaigns = await meta.listCampaigns(50);
      summary.calls += 1;
      summary.campaignsSeen = campaigns.length;

      for (const campaign of campaigns.slice(0, 5)) {
        try {
          await meta.getCampaignInsights(campaign.id);
          summary.calls += 1;
          summary.insightsFetched += 1;
        } catch (err) {
          summary.errors.push((err as Error).message);
        }
      }
    } catch (err) {
      summary.errors.push((err as Error).message);
    }

    try {
      forms = await meta.listLeadForms();
      summary.calls += 1;
      summary.formsSeen = forms.length;

      for (const form of forms.slice(0, 3)) {
        try {
          const leads = await meta.listLeadsForForm(form.id, { limit: 25 });
          summary.calls += 1;
          summary.leadsFetched += leads.length;
        } catch (err) {
          summary.errors.push((err as Error).message);
        }
      }
    } catch (err) {
      summary.errors.push((err as Error).message);
    }

    if (createDraftCampaigns) {
      for (let n = 0; n < campaignsPerRound; n++) {
        try {
          const created = await createProbeCampaign({
            businessId: business.id,
            businessName: business.name,
            businessWebsite: business.website,
            round: i,
            forms,
          });
          if (created.created) {
            summary.calls += 4;
            summary.campaignsCreated += 1;
            totalCreated += 1;
          } else if (created.reason) {
            summary.errors.push(created.reason);
          }
        } catch (err) {
          summary.errors.push((err as Error).message);
        }
      }
    }

    totalCalls += summary.calls;
    roundsSummary.push(summary);
  }

  await logEvent({
    businessId: business.id,
    action: "meta.traffic.run",
    entityType: "campaign",
    reason: `Ran internal traffic generator for ${rounds} round(s)`,
    details: {
      rounds,
      createDraftCampaigns,
      campaignsPerRound,
      totalCalls,
      totalCreated,
      perRound: roundsSummary,
    },
  });

  const status = totalCalls > 0 ? 200 : 502;
  const metaError = status === 502 ? "No successful Meta API calls were completed." : null;

  return NextResponse.json(
    {
      ok: status === 200,
      error: metaError,
      businessId: business.id,
      rounds,
      createDraftCampaigns,
      campaignsPerRound,
      totalCalls,
      totalCreated,
      roundsSummary,
    },
    { status },
  );
}
